`computeNext()` should not cause a side-effect in the normal case
jenkinsci/workflow-api-plugin pull request #304
Opened 2023-08-25 11:25 UTC by Vlatombe

cf. https://github.com/jenkinsci/kubernetes-plugin/pull/1342#issuecomment-1692993104

### Testing done

AFAIU to reproduce the issue would require to set up a cloud agent. On its termination, it calls indirectly `computeNext()` which unregisters the `FlowExecutionOwner` if it is the last node in the pipeline. Then the regular `unregister` call when the `WorkflowRun` completes now issues a warning because it has already been unregistered.

```[tasklist]
### Submitter checklist
- [X] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [X] Ensure that the pull request title represents the desired changelog entry
- [X] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

2023-08-25 13:21 UTC, jglick requested changes
Idea seems right, but we want to keep the `unregister` call from https://github.com/jenkinsci/workflow-api-plugin/blob/4521fef5822dd23c5713fede0a7faf82be73a4b4/src/main/java/org/jenkinsci/plugins/workflow/flow/FlowExecutionList.java#L198-L213 (in some form) as this cleans up stale entries.

2023-08-25 13:21 UTC, jglick commented on src/main/java/org/jenkinsci/plugins/workflow/flow/FlowExecutionList.java
> +                        return o.get();
You need to keep the check for `o.isComplete()` but just `continue` (or do nothing) in that case, to find the next one (if any) which is _not_ complete.

2023-08-25 14:50 UTC, jglick requested changes

2023-08-25 14:50 UTC, jglick commented on src/main/java/org/jenkinsci/plugins/workflow/flow/FlowExecutionList.java
> +                if (e.isComplete()) {
This will never happen because you are skipping complete executions. There would need to be an alternate iteration method or something.

2023-08-25 15:04 UTC, Vlatombe commented on src/main/java/org/jenkinsci/plugins/workflow/flow/FlowExecutionList.java
> +                    unregister(o);
Yikes that's going to fail as well

2023-08-28 09:10 UTC, Vlatombe commented
@dwnusbaum can you help with review/merge of this fix? Currently holds up another series of PRs (e.g. https://github.com/jenkinsci/kubernetes-plugin/pull/1342)

2023-08-28 14:31 UTC, dwnusbaum approved these changes

2023-08-28 14:33 UTC, dwnusbaum commented
@Vlatombe Did you check this against tests in `workflow-cps` and `workflow-job` since the new code seems to be not well covered by existing tests in this plugin? I can check it in a minute if you haven't already.

2023-08-28 14:57 UTC, dwnusbaum commented
> To cover the new lines would require a test pipeline involving cloud agents

It should be possible to set up a relevant test with `@LocalData` and/or a custom Pipeline step, but either way I mainly just wanted to make sure it didn't affect existing tests in those plugins, and from a quick local check things seem ok.

2023-08-28 15:03 UTC, merged